Step three
elijah0107/my_project pull request #3
Opened 2018-11-21 18:45 UTC by elijah0107

2018-11-22 06:10 UTC, mtrsv requested changes

2018-11-22 06:10 UTC, mtrsv commented on src/styles.scss
> +  .search_sid {
Классы пишем через -

2018-11-22 06:10 UTC, mtrsv commented on src/styles.scss
>  body {
Зачем?

2018-11-22 06:10 UTC, mtrsv commented on src/styles.scss
> +    h2 {
Не привязываемся к тэгам, только к классам

2018-11-22 16:32 UTC, elijah0107 commented on src/styles.scss
> +    h2 {
fix

2018-11-22 16:32 UTC, elijah0107 commented on src/styles.scss
>  body {
убрал

2018-11-22 16:33 UTC, elijah0107 commented on src/styles.scss
> +  .search_sid {
поправил

2018-11-24 05:08 UTC, mtrsv approved these changes

2019-01-08 13:28 UTC, merged