New step
elijah0107/my_project pull request #4
Opened 2019-02-13 04:43 UTC by elijah0107

2019-02-13 09:52 UTC, mtrsv requested changes

2019-02-13 09:52 UTC, mtrsv commented on src/index.js
> +window._ = lodash;
Зачем так? Если нужно использовать методы лодаша, лучше их импортировать напрямую:
import omit from 'lodash/omit'

2019-02-13 09:52 UTC, mtrsv commented on src/index.js
> +    window.App = {
Для чего нужны глобальные переменные?
Лучше каждый класс описать в отдельном файле и имрортировать там, где нужно.

2019-02-13 09:52 UTC, mtrsv commented on src/index.js
> +            let valueInput = $('.text-value').val();
jQuery лучше использовать через this.$, чтобы вьюха влияла только на свой элемент. Еще несколько мест в файле.

2019-02-14 09:09 UTC, krutoo commented on src/components/search-form.js
> +import $ from "jquery";
Двойные кавычки а выше одинарные, не критично

2019-02-14 09:11 UTC, krutoo commented on spec/testItems.spec.js
> +
Пустой тест

2019-02-14 09:11 UTC, krutoo commented on src/index.js
> +// import omit from 'lodash';
если не нужен - лучше удалить комментарий

2019-02-14 09:12 UTC, elijah0107 commented on src/index.js
> +            let valueInput = $('.text-value').val();
поправил

2019-02-14 09:12 UTC, elijah0107 commented on src/index.js
> +    window.App = {
поправил

2019-02-14 09:12 UTC, elijah0107 commented on src/index.js
> +window._ = lodash;
поправил

2019-02-14 09:31 UTC, elijah0107 commented on src/components/search-form.js
> +import $ from "jquery";
Поправил

2019-02-14 09:31 UTC, elijah0107 commented on spec/testItems.spec.js
> +
Пока что убрал

2019-02-14 09:31 UTC, elijah0107 commented on src/index.js
> +// import omit from 'lodash';
убрал

2019-02-14 09:53 UTC, krutoo commented on src/components/items.js
> +export default Items;
Нет пустой строки, на это указывает красная иконка в конце.
Можно настроить редактор на автоматическое добавление при сохранении.

2019-02-14 09:58 UTC, elijah0107 commented on src/components/items.js
> +export default Items;
Добавил

2019-02-14 11:35 UTC, krutoo approved these changes

2019-02-15 06:33 UTC, mtrsv approved these changes

2019-02-15 07:09 UTC, merged