BB-5 Вью для карточки товара
elijah0107/my_project pull request #5
Opened 2019-02-25 12:33 UTC by elijah0107

- Сделал вью для карточки
- Реализовал вывод описания, фото, характеристик

2019-02-26 03:34 UTC, krutoo commented on src/index.js
> +import CartsItem from './components/carts-item';
Где-то есть точки с запятыми, где-то нет, не кртитчно

2019-02-26 03:34 UTC, krutoo commented on src/components/search-form.js
> +        let sid = this.$(event.target).data('item-sid');
Там где переменная не будет меняться по ходу функции можно использовать const вместо let, не критично

2019-02-26 03:34 UTC, krutoo commented on src/components/cart-view.js
> +            $('.cart-item').removeClass('not-display');
Возможно стоит искать прямо внутри элемента view, тогда не пригодится jQuery

2019-02-26 03:34 UTC, krutoo commented on src/components/cart-view.js
> +                    expand: 'description, photo_sizes'
По соглашению используем запятые в конце на всех строках, не критично

2019-02-26 03:34 UTC, krutoo commented on index.html
> +                        <div class="trademark">Состав:__________________<%= stuff %></div>
Лучше стилями сделать элемент который будет иметь border-bottom и растягиваться между двумя элементами: наименованием атрибута и значением.

2019-02-26 03:34 UTC, krutoo commented on index.html
> +                    <div class="titles characteristic"><a class="titles characteristic" href="#">ХАРАКТЕРИСТИКИ</a></div>
Заглавные буквы лучше определить стилями, не критично

2019-02-26 03:34 UTC, krutoo commented on index.html
>  <link rel='stylesheet' href='dist/style.css'>
теги link лучше располагать в разделе head

2019-02-26 04:33 UTC, elijah0107 commented on src/index.js
> +import CartsItem from './components/carts-item';
поправил

2019-02-26 04:33 UTC, elijah0107 commented on src/components/search-form.js
> +        let sid = this.$(event.target).data('item-sid');
поправил

2019-02-26 04:33 UTC, elijah0107 commented on src/components/cart-view.js
> +                    expand: 'description, photo_sizes'
поправил

2019-02-26 04:34 UTC, elijah0107 commented on index.html
> +                    <div class="titles characteristic"><a class="titles characteristic" href="#">ХАРАКТЕРИСТИКИ</a></div>
поправил

2019-02-26 04:34 UTC, elijah0107 commented on index.html
>  <link rel='stylesheet' href='dist/style.css'>
поправил

2019-02-26 05:54 UTC, mtrsv requested changes

2019-02-26 05:54 UTC, mtrsv commented on src/styles.scss
> +            .description-value, .characteristic-value {
ЛУчше второй класс перенести на следующую строку

2019-03-01 04:51 UTC, elijah0107 commented on src/styles.scss
> +            .description-value, .characteristic-value {
Поправил

2019-03-01 04:51 UTC, elijah0107 commented on index.html
> +                        <div class="trademark">Состав:__________________<%= stuff %></div>
Сделал

2019-03-01 04:52 UTC, elijah0107 commented on src/components/cart-view.js
> +            $('.cart-item').removeClass('not-display');
Изменил

2019-03-01 04:53 UTC, krutoo approved these changes

2019-03-01 06:11 UTC, mtrsv approved these changes

2019-03-01 06:14 UTC, merged