BB-6  Добавить в проект Jest, написать тесты на модель и вью. Протестировать каждый метод. Все последующие задачи должны включать тесты
elijah0107/my_project pull request #6
Opened 2019-03-12 18:03 UTC by elijah0107

Добавил jest тесты на каждый метод

2019-03-13 04:11 UTC, krutoo commented on src/components/product-view.js
> +        'click .description': 'openDescription'
нужна запятая в конце, можено добавить ESLint чтобы ругался на такое

2019-03-13 04:11 UTC, krutoo commented on tests/product.test.js
> +
странная пустая строка, можно добавить правило для ESLint, вроде padded blocks

2019-03-13 04:11 UTC, krutoo commented on tests/search.test.js
> +import $ from "jquery";
То одинарные, то двойные кавычки, можно добавить правило для ESLint

2019-03-13 04:11 UTC, krutoo commented on tests/search.test.js
> +
Странная пустая строка

2019-03-13 05:39 UTC, elijah0107 commented on tests/search.test.js
> +import $ from "jquery";
Добавил

2019-03-13 05:39 UTC, elijah0107 commented on tests/product.test.js
> +
Сделал

2019-03-13 05:39 UTC, elijah0107 commented on src/components/product-view.js
> +        'click .description': 'openDescription'
Сделал

2019-03-13 05:39 UTC, elijah0107 commented on tests/search.test.js
> +
убрал

2019-03-13 05:50 UTC, krutoo commented on src/components/search-form.js
> +    'click #first-search': 'editSearch',
давай подписываться на классы с префиксом "js-"

2019-03-13 07:00 UTC, elijah0107 commented on src/components/search-form.js
> +    'click #first-search': 'editSearch',
Давай

2019-03-13 07:25 UTC, krutoo commented on src/components/product-view.js
> +    $('.js-characteristic').addClass('selected');
Этот элемент относится к этой view?
Если нет тогда лучше сообщить view, которая им управляет что пора переключить состояние.
Если да, то лучше через this.$

2019-03-13 16:19 UTC, elijah0107 commented on src/components/product-view.js
> +    $('.js-characteristic').addClass('selected');
Переделал

2019-03-14 03:23 UTC, mtrsv requested changes

2019-03-14 03:23 UTC, mtrsv commented on jest.config.js
> +
Лишняя строка

2019-03-14 03:23 UTC, mtrsv commented on src/styles.scss
> +.js-description:visited,
Если вешать js- префикс на классы со стилями, теряется весь смысл его использования. 
По идее префикс js- должен сказать нам, что класс используется только в скриптах и на нем нет стилей.

2019-03-14 03:23 UTC, mtrsv commented on tests/product.test.js
> +        name: 'test',
Если атрибуты модели не влияют на функционал, можно не заполнять

2019-03-14 03:53 UTC, elijah0107 commented on tests/product.test.js
> +        name: 'test',
Без них не работает

2019-03-14 03:53 UTC, elijah0107 commented on src/styles.scss
> +.js-description:visited,
Поправил

2019-03-14 03:54 UTC, elijah0107 commented on jest.config.js
> +
Убрал

2019-03-14 04:21 UTC, krutoo commented on src/components/search-form.js
> +    'click #js-first-search': 'editSearch',
Лучше подписываться именно на классы

2019-03-14 04:35 UTC, elijah0107 commented on src/components/search-form.js
> +    'click #js-first-search': 'editSearch',
Сделал классы

2019-03-14 09:42 UTC, krutoo commented on .eslintrc.yml
> +  indent: off
Раз появился конфиг ESLint, стоит определиться с индентацией, предлагаю мягкую в два пробела

2019-03-14 11:26 UTC, elijah0107 commented on .eslintrc.yml
> +  indent: off
Сделал индентацию

2019-03-15 04:06 UTC, krutoo approved these changes

2019-03-15 04:14 UTC, mtrsv approved these changes

2019-03-15 04:16 UTC, merged